//
//  LeftMenuPresenter.swift
//  contentstack-ecommerce-app
//
//  Created by Uttam Ukkoji on 03/12/18.
//  Copyright (c) 2018 Contentstack. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LeftMenuPresentationLogic
{
  func show(response: LeftMenu.CategoryModal.Response)
}

class LeftMenuPresenter: LeftMenuPresentationLogic
{
  weak var viewController: LeftMenuDisplayLogic?
  
  // MARK: Do CategoryModal
  
  func show(response: LeftMenu.CategoryModal.Response)
  {
    viewController?.displayCategoryModal(response: response)
  }
}
