//
//  ProductDetailModels.swift
//  contentstack-ecommerce-app
//
//  Created by Uttam Ukkoji on 03/12/18.
//  Copyright (c) 2018 Contentstack. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ProductDetail
{
    // MARK: Use cases
    
    struct Request
    {
        let fetchRequet = Product.productFetchRequest()
        let productID : String
    }
    struct Response
    {
        var product : Product? = nil
    }
    struct ViewModel
    {
        struct ProductInfo {
            var imageUrl : String?
            var title: String?
        }
        struct ProductPrice {
            var price : Double = 0
            var offerPrice: Double = 0
        }
        struct ProductDesc {
            var string : NSAttributedString?
            var isInStock: Bool = false
            var relatedProducts: [String]?
        }
        
        var productDetailArray : [Any] = []
        
        func numberOfSection() -> Int {
            return productDetailArray.count
        }
        
        func numberOfRow(in section: Int) -> Int {
            return 1
        }
    }
    
}

