//
//  ProductDetailInteractor.swift
//  contentstack-ecommerce-app
//
//  Created by Uttam Ukkoji on 03/12/18.
//  Copyright (c) 2018 Contentstack. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductDetailBusinessLogic
{
    func getProduct(request: ProductDetail.Request)
    func showRelated(products: [String])
}

protocol ProductDetailDataStore
{
    var productID: String {get set}
    var products: [String] {get set}
    //var name: String { get set }
}

class ProductDetailInteractor: ProductDetailBusinessLogic, ProductDetailDataStore
{
    var presenter: ProductDetailPresentationLogic?
    var worker: ProductDetailWorker?
    var productID: String = ""
    var products: [String] = []
    // MARK: Do something
    
    func getProduct(request: ProductDetail.Request) {
        worker = ProductDetailWorker()
        presenter?.showProductList(response: worker!.fetchProduct(request: request))
    }
    
    func showRelated(products: [String]) {
        self.products = products
        presenter?.showRelatedProduct()
    }
}

