//
//  ProductDetailRouter.swift
//  contentstack-ecommerce-app
//
//  Created by Uttam Ukkoji on 03/12/18.
//  Copyright (c) 2018 Contentstack. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ProductDetailRoutingLogic
{
    func routeToshow_productListWithSegue(_ segue: UIStoryboardSegue?)
}

protocol ProductDetailDataPassing
{
    var dataStore: ProductDetailDataStore? { get }
}

class ProductDetailRouter: NSObject, ProductDetailRoutingLogic, ProductDetailDataPassing
{
    weak var viewController: ProductDetailViewController?
    var dataStore: ProductDetailDataStore?
    
    // MARK: Routing
    
    func routeToshow_productListWithSegue(_ segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! ProductListSenceViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        }
    }
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: ProductDetailViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    func passDataToSomewhere(source: ProductDetailDataStore, destination: inout ProductListSenceDataStore)
    {
        destination.products = source.products
    }
}

