//
//  ProductListSenceInteractor.swift
//  contentstack-ecommerce-app
//
//  Created by Uttam Ukkoji on 03/12/18.
//  Copyright (c) 2018 Contentstack. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData
import ContentstackSwift
protocol ProductListSenceBusinessLogic
{
    func getProductsList(request: ProductListSence.Products.Request)
    func fetchProductList(request: ProductListSence.Products.Request)
    func showProductDetails(productId : String)
}

protocol ProductListSenceDataStore
{
    var productID : String {get}
    var products: [String] {get set}

}

class ProductListSenceInteractor: ProductListSenceBusinessLogic, ProductListSenceDataStore
{
    
    var productID: String = ""
    var products: [String] = []

    var presenter: ProductListSencePresentationLogic?
    var worker: ProductListSenceWorker?
    
    // MARK: Do something
    func getProductsList(request: ProductListSence.Products.Request) {
        worker = ProductListSenceWorker()
        worker?.getProduct(request: request, onCompletion: { (queryResult, error) -> (Void) in
            guard let qResult = queryResult else {return}
            let result = qResult.items
            let backgroundContext = AppDelegate.shared.persistentContainer.newBackgroundContext()
            
            for entry in result {
                let predicate = NSPredicate(format: "uid = %@", entry.uid)
                let product = backgroundContext.findOrCreate(Product.self, predicate: predicate)
                product.uid = entry.uid
                product.title = entry.title
                product.desc = entry.fields?["description"] as? String
                product.categories = request.categoryID
                if let relatedProduct = entry.fields?["related_products"] as? [String] {
                    product.relatedProducts = relatedProduct
                }
                if let featuredImage = entry.fields?["featured_image"] as? [AssetModel], featuredImage.count > 0  {
                    product.featuredImage = featuredImage[0].url
                }
                product.in_stock = entry.fields?["in_stock"] as? Bool ?? false
                product.price = entry.fields?["price"] as? Double ?? 0
                product.offetPrice = entry.fields?["offer_price"] as? Double ?? 0
                product.date = entry.updatedAt
            }
            do {
                try backgroundContext.save()
            }catch {
                
            }
            self.presenter?.loadProductList(request: request)
        })
    }
    
    func fetchProductList(request: ProductListSence.Products.Request) {
        worker = ProductListSenceWorker()
        let response = worker!.fetchProduct(request: request)
        presenter?.showProductList(response: response)
    }
    
    func showProductDetails(productId: String) {
        self.productID = productId
        presenter?.showProductDetails()
    }
}

