//
//  ProductListSenceModels.swift
//  contentstack-ecommerce-app
//
//  Created by Uttam Ukkoji on 03/12/18.
//  Copyright (c) 2018 Contentstack. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ProductListSence
{
  // MARK: Use cases
  
  enum Products
  {
    struct Request
    {
        let categoryID: String?
        let productList: [String]?
        let productQuery = APIManger.stack.contentType(withName: "product").query()
        let fetchRequest = Product.productFetchRequest()
    }
    struct Response
    {
        var productArray : [Product] = []
    }
    struct ViewModel
    {
        
    }
  }
}
