//
//  ProductListSenceRouter.swift
//  contentstack-ecommerce-app
//
//  Created by Uttam Ukkoji on 03/12/18.
//  Copyright (c) 2018 Contentstack. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ProductListSenceRoutingLogic
{
    func routeToshow_detailsWithSegue(_ segue: UIStoryboardSegue?)
}

protocol ProductListSenceDataPassing
{
    var dataStore: ProductListSenceDataStore? { get }
}

class ProductListSenceRouter: NSObject, ProductListSenceRoutingLogic, ProductListSenceDataPassing
{
    weak var viewController: ProductListSenceViewController?
    var dataStore: ProductListSenceDataStore?
    
    // MARK: Routing
    func routeToshow_detailsWithSegue(_ segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! ProductDetailViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        }
    }
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: ProductListSenceViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    func passDataToSomewhere(source: ProductListSenceDataStore, destination: inout ProductDetailDataStore)
    {
        destination.productID = source.productID
    }
}

