//
//  ProductListSenceWorker.swift
//  contentstack-ecommerce-app
//
//  Created by Uttam Ukkoji on 03/12/18.
//  Copyright (c) 2018 Contentstack. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Contentstack
class ProductListSenceWorker
{
    func getProduct (request: ProductListSence.Products.Request, onCompletion: @escaping ((QueryResult?, Error?)-> (Swift.Void)))
    {
        let query = request.productQuery
        if let id = request.categoryID {
            query.whereKey("categories", equalTo: id)
        }
        query.find { (responseType, queryResult, error) in
            onCompletion(queryResult, error)
        }
    }
    
    func fetchProduct(request: ProductListSence.Products.Request) -> ProductListSence.Products.Response {
        let fetchRequest = request.fetchRequest
        if let id = request.categoryID {
            let predicate = NSPredicate(format: " categories = %@", id)
            fetchRequest.predicate = predicate
        }else if let ids = request.productList {
            let predicate = NSPredicate(format: " uid in %@", ids)
            fetchRequest.predicate = predicate
        }
        fetchRequest.sortDescriptors = [NSSortDescriptor(key: "date", ascending: false)]
        var resonse = ProductListSence.Products.Response()
        do {
        let products = try AppDelegate.shared.persistentContainer.viewContext.fetch(fetchRequest)
            resonse.productArray = products
        }catch {
            
        }
        return resonse
    }
}

