//
//  ProductListSenceWorker.swift
//  contentstack-ecommerce-app
//
//  Created by Uttam Ukkoji on 03/12/18.
//  Copyright (c) 2018 Contentstack. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import ContentstackSwift
class ProductListSenceWorker
{
    func getProduct (request: ProductListSence.Products.Request, onCompletion: @escaping ((ContentstackResponse<EntryModel>?, Error?)-> (Swift.Void)))
    {
        let query = request.productQuery
        if let id = request.categoryID {
           _ = query.where(valueAtKey: "categories", .equals(id))
        }
        query.find { (result: Result<ContentstackResponse<EntryModel>, Error>, responseType) in
            DispatchQueue.main.async {
                switch result {
                case .success(let response):
                    onCompletion(response, nil)
                case .failure(let error):
                    onCompletion(nil, error)
                }
            }
        }
    }
    
    func fetchProduct(request: ProductListSence.Products.Request) -> ProductListSence.Products.Response {
        let fetchRequest = request.fetchRequest
        if let id = request.categoryID {
            let predicate = NSPredicate(format: " categories = %@", id)
            fetchRequest.predicate = predicate
        }else if let ids = request.productList {
            let predicate = NSPredicate(format: " uid in %@", ids)
            fetchRequest.predicate = predicate
        }
        fetchRequest.sortDescriptors = [NSSortDescriptor(key: "date", ascending: false)]
        var resonse = ProductListSence.Products.Response()
        do {
        let products = try AppDelegate.shared.persistentContainer.viewContext.fetch(fetchRequest)
            resonse.productArray = products
        }catch {
            
        }
        return resonse
    }
}

